# Generated by Django 6.0 on 2026-01-06 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiderKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Gider Türü')),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': '4. Gider Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İmalat Kategorisi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'İmalat Kategorisi',
                'verbose_name_plural': '1. İmalat Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_unvani', models.CharField(max_length=200, verbose_name='Firma Ünvanı')),
                ('yetkili_kisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yetkili')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
            },
        ),
        migrations.CreateModel(
            name='Harcama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Harcama Açıklaması')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('kur_degeri', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Kur')),
                ('belge', models.FileField(blank=True, null=True, upload_to='harcamalar/', verbose_name='Fiş/Fatura')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcamalar', to='core.giderkategorisi', verbose_name='Gider Türü')),
            ],
            options={
                'verbose_name': 'Harcama / Masraf',
                'verbose_name_plural': '5. Harcamalar (Fiş & Fatura)',
            },
        ),
        migrations.CreateModel(
            name='IsKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='İş Kalemi Adı')),
                ('hedef_miktar', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Miktar')),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('m2', 'm²'), ('m3', 'm³'), ('mt', 'Metre'), ('kg', 'Kg'), ('ton', 'Ton'), ('set', 'Set'), ('adam_saat', 'Adam/Saat')], default='adet', max_length=20, verbose_name='Birim')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İş Kalemi',
                'verbose_name_plural': '2. İş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('kur_degeri', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Kur Değeri')),
                ('teklif_dosyasi', models.FileField(blank=True, null=True, upload_to='teklifler/', verbose_name='Teklif PDF')),
                ('is_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.iskalemi', verbose_name='İş Kalemi')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Alınan Teklif',
                'verbose_name_plural': '3. Teklifler (İcmal)',
            },
        ),
    ]
