# Generated by Django 6.0.1 on 2026-01-16 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Depo Adı')),
                ('tur', models.CharField(choices=[('merkez', '🏢 Merkez Depo (Ana Stok)'), ('baglanti', '🔗 Bağlantı Deposu (Tedarikçide)'), ('kullanim', '🔨 Kullanım Deposu (Şantiye/Tüketim)')], default='merkez', max_length=20, verbose_name='Depo Türü')),
                ('adres', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Depo Tanımı',
                'verbose_name_plural': 'Depo Tanımları',
            },
        ),
        migrations.CreateModel(
            name='GiderKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Gider Kategorisi')),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Hakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakedis_no', models.PositiveIntegerField()),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('onceki_toplam_yuzde', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bu_donem_yuzde', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bu Dönem İlerleme (%)')),
                ('kümülatif_yuzde', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Toplam İlerleme (%)')),
                ('hakedis_tutari', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hakediş Tutarı (KDV Hariç)')),
                ('kesintiler_toplami', models.DecimalField(decimal_places=2, default=0, help_text='Avans, Stopaj vb.', max_digits=15)),
                ('odenmesi_gereken', models.DecimalField(decimal_places=2, max_digits=15)),
                ('onaylandi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Malzeme Adı')),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('mt', 'Metre (mt)'), ('adam_saat', 'Adam/Saat'), ('goturu', 'Götürü (Toplu)')], default='adet', max_length=20)),
                ('marka', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('kritik_stok', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SatinAlma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('toplam_miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('teslim_edilen', models.DecimalField(decimal_places=2, default=0, help_text='Depoya giren miktar', max_digits=10)),
                ('aciklama', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_unvani', models.CharField(max_length=200, verbose_name='Firma Ünvanı')),
                ('yetkili', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('aciklama', models.CharField(blank=True, max_length=200)),
                ('hedef_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giris_transferleri', to='core.depo')),
                ('kaynak_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cikis_transferleri', to='core.depo')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.malzeme')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=50, verbose_name='Fatura No')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('son_odeme_tarihi', models.DateField(blank=True, null=True)),
                ('tutar_kdv_haric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kdv_tutari', models.DecimalField(decimal_places=2, max_digits=15)),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ödenecek Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3)),
                ('kur', models.DecimalField(decimal_places=4, default=1.0, help_text='Fatura tarihindeki kur', max_digits=10)),
                ('dosya', models.FileField(blank=True, null=True, upload_to='faturalar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hakedis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturalar', to='core.hakedis')),
                ('siparis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturalar', to='core.satinalma')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='core.tedarikci')),
            ],
        ),
        migrations.CreateModel(
            name='Harcama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Harcama Açıklaması')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3)),
                ('kur', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('dekont', models.FileField(blank=True, null=True, upload_to='harcamalar/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcamalar', to='core.giderkategorisi')),
            ],
            options={
                'verbose_name': 'Genel Gider (Harcama)',
                'verbose_name_plural': 'Genel Giderler (Harcama)',
            },
        ),
        migrations.CreateModel(
            name='IsKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='İş Kalemi Adı')),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('mt', 'Metre (mt)'), ('adam_saat', 'Adam/Saat'), ('goturu', 'Götürü (Toplu)')], default='adet', max_length=20)),
                ('aciklama', models.TextField(blank=True, verbose_name='Teknik Şartname')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='DepoHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('giris', '📥 Giriş (Satınalma)'), ('cikis', '📤 Çıkış (Tüketim)'), ('transfer', '🔄 Transfer'), ('iade', '↩️ İade')], max_length=20)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('aciklama', models.CharField(blank=True, max_length=300)),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='core.depo')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hareket_loglari', to='core.depotransfer')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='core.malzeme')),
            ],
        ),
        migrations.CreateModel(
            name='MalzemeTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İstenen Miktar')),
                ('proje_yeri', models.CharField(blank=True, max_length=200, verbose_name='Kullanılacak Yer')),
                ('durum', models.CharField(choices=[('bekliyor', '⏳ Onay Bekliyor'), ('islemde', '⚙️ Satınalma Sürecinde'), ('tamamlandi', '✅ Tamamlandı'), ('iptal', '❌ İptal')], default='bekliyor', max_length=20)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('aciklama', models.TextField(blank=True)),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='core.malzeme')),
                ('talep_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hakedis',
            name='sozlesme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hakedisler', to='core.satinalma'),
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('odeme_turu', models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale / EFT'), ('cek', 'Çek')], default='havale', max_length=10)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3)),
                ('kur', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('banka_adi', models.CharField(blank=True, max_length=100)),
                ('cek_no', models.CharField(blank=True, max_length=50)),
                ('vade_tarihi', models.DateField(blank=True, null=True)),
                ('cek_durumu', models.CharField(choices=[('beklemede', '⏳ Müşteride / Bekliyor'), ('tahsil_edildi', '✅ Tahsil Edildi (Hesaptan Düştü)'), ('karsiliksiz', '❌ Karşılıksız / İade')], default='beklemede', max_length=20)),
                ('aciklama', models.CharField(blank=True, max_length=200)),
                ('bagli_fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odemeler', to='core.fatura')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odemeler', to='core.tedarikci')),
            ],
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3)),
                ('kdv_orani', models.IntegerField(default=20, verbose_name='KDV (%)')),
                ('kdv_dahil_mi', models.BooleanField(default=False)),
                ('durum', models.CharField(choices=[('beklemede', '⏳ Değerlendiriliyor'), ('onaylandi', '✅ Onaylandı (Sipariş)'), ('reddedildi', '❌ Reddedildi')], default='beklemede', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_kalemi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.iskalemi')),
                ('malzeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.malzeme')),
                ('talep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.malzemetalep')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.tedarikci')),
            ],
        ),
        migrations.AddField(
            model_name='satinalma',
            name='teklif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siparis', to='core.teklif'),
        ),
    ]
