# Generated by Django 6.0 on 2026-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='durum',
            field=models.CharField(choices=[('beklemede', '⏳ Beklemede'), ('onaylandi', '✅ Onaylandı'), ('reddedildi', '❌ Reddedildi')], default='beklemede', max_length=20, verbose_name='Onay Durumu'),
        ),
    ]
