# Generated by Django 6.0.1 on 2026-01-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depo',
            options={'verbose_name_plural': 'Depo Tanımları'},
        ),
        migrations.RemoveField(
            model_name='depo',
            name='tur',
        ),
        migrations.AddField(
            model_name='depo',
            name='depo_turu',
            field=models.CharField(choices=[('MERKEZ', 'Merkez Depo'), ('BAGLANTI', 'Bağlantı Deposu (Sanal/Tedarikçi)'), ('KULLANIM', 'Kullanım Deposu (Sahada)')], default='MERKEZ', max_length=10, verbose_name='Depo Türü'),
        ),
        migrations.AddField(
            model_name='depo',
            name='is_sanal',
            field=models.BooleanField(default=False, verbose_name='Sanal / Tedarikçi Deposu mu?'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='kdv_orani',
            field=models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='KDV Oranı'),
        ),
        migrations.AlterField(
            model_name='depo',
            name='adres',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lokasyon / Adres'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='kdv_orani',
            field=models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20')], default=20, verbose_name='KDV (%)'),
        ),
    ]
