# Generated by Django 6.0.1 on 2026-01-16 15:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_depo_options_remove_depo_tur_depo_depo_turu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('kur', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18)),
                ('tarih', models.DateField(blank=True, null=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odeme_dagitimi', to='core.fatura')),
                ('odeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_dagitimi', to='core.odeme')),
            ],
            options={
                'verbose_name': 'Fatura-Ödeme Dağıtımı',
                'verbose_name_plural': 'Fatura-Ödeme Dağıtımları',
            },
        ),
    ]
