# Generated by Django 6.0 on 2026-01-06 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teklif_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Ödeme Tarihi')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama (Örn: 1. Taksit, Avans)')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ödenen Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('kur_degeri', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='İşlem Kuru')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='dekontlar/', verbose_name='Dekont / Makbuz')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='core.tedarikci', verbose_name='Tedarikçi Firma')),
            ],
            options={
                'verbose_name': 'Yapılan Ödeme',
                'verbose_name_plural': '6. Tedarikçi Ödemeleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
