# Generated by Django 6.0 on 2026-01-06 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_odeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='cek_banka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banka Adı'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='cek_gorseli',
            field=models.FileField(blank=True, null=True, upload_to='cekler/', verbose_name='Çek Görseli Yükle'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='cek_numarasi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çek Seri No'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='cek_sube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube / Hesap'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='cek_vade_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Çek Vade Tarihi'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='odeme_turu',
            field=models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale / EFT'), ('cek', 'Çek / Senet')], default='havale', max_length=10, verbose_name='Ödeme Türü'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='kdv_orani',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Örn: 18, 20, 21.5 veya 0 giriniz.', max_digits=5, verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='tutar',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='aciklama',
            field=models.CharField(max_length=200, verbose_name='Açıklama (Örn: 1. Hakediş)'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='dekont',
            field=models.FileField(blank=True, null=True, upload_to='dekontlar/', verbose_name='Dekont Yükle'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat (KDV HARİÇ)'),
        ),
    ]
