# Generated by Django 6.0 on 2026-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_odeme_cek_banka_odeme_cek_gorseli_odeme_cek_numarasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='kdv_dahil_mi',
            field=models.BooleanField(default=False, help_text="Eğer işaretlerseniz, sistem KDV'yi fiyattan düşüp NET rakamı kaydeder.", verbose_name='Bu fiyata KDV Dahil mi?'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat'),
        ),
    ]
