# Generated by Django 6.0 on 2026-01-06 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teklif_kdv_dahil_mi_alter_teklif_birim_fiyat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giderkategorisi',
            options={'verbose_name_plural': 'Gider Kategorileri (OPEX)'},
        ),
        migrations.AlterModelOptions(
            name='harcama',
            options={'verbose_name_plural': '4. Gider / Harcama Fişleri'},
        ),
        migrations.AlterModelOptions(
            name='iskalemi',
            options={'verbose_name_plural': '2. İş Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. İmalat Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='odeme',
            options={'verbose_name_plural': '5. Tedarikçi Ödemeleri'},
        ),
        migrations.AlterModelOptions(
            name='tedarikci',
            options={'verbose_name_plural': 'Tedarikçiler / Taşeronlar'},
        ),
        migrations.AlterModelOptions(
            name='teklif',
            options={'verbose_name_plural': '3. Teklifler (İcmal)'},
        ),
        migrations.RemoveField(
            model_name='harcama',
            name='belge',
        ),
        migrations.RemoveField(
            model_name='harcama',
            name='kur_degeri',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='harcama',
            name='dekont',
            field=models.FileField(blank=True, null=True, upload_to='harcamalar/'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='ilgili_teklif',
            field=models.ForeignKey(blank=True, help_text='Eğer bu ödeme belirli bir iş için yapılıyorsa seçiniz.', limit_choices_to={'durum': 'onaylandi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teklif', verbose_name='İlgili İş / Sözleşme (Opsiyonel)'),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='adres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teklif',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giderkategorisi',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='aciklama',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcamalar', to='core.giderkategorisi'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='tutar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='iskalemi',
            name='birim',
            field=models.CharField(choices=[('adet', 'Adet'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('mt', 'Metre (mt)'), ('adam_saat', 'Adam/Saat'), ('goturu', 'Götürü (Toplu)')], default='adet', max_length=20),
        ),
        migrations.AlterField(
            model_name='iskalemi',
            name='hedef_miktar',
            field=models.FloatField(default=1, verbose_name='Yaklaşık Metraj'),
        ),
        migrations.AlterField(
            model_name='iskalemi',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.kategori'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='cek_banka',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Banka Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odeme',
            name='cek_gorseli',
            field=models.ImageField(blank=True, null=True, upload_to='cekler/'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='cek_numarasi',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Çek No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odeme',
            name='cek_sube',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Şube'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odeme',
            name='dekont',
            field=models.FileField(blank=True, null=True, upload_to='odemeler/'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='odeme_turu',
            field=models.CharField(choices=[('nakit', 'Nakit / Havale'), ('cek', 'Çek'), ('kk', 'Kredi Kartı')], default='nakit', max_length=10, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ödeme Tarihi'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tedarikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='core.tedarikci'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tutar',
            field=models.FloatField(verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='tedarikci',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tedarikci',
            name='yetkili_kisi',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Yetkili Kişi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teklif',
            name='birim_fiyat',
            field=models.FloatField(verbose_name='Birim Fiyat (KDV Hariç)'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='durum',
            field=models.CharField(choices=[('beklemede', '⏳ Beklemede'), ('onaylandi', '✅ Onaylandı / Sözleşme'), ('reddedildi', '❌ Reddedildi')], default='beklemede', max_length=20),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='is_kalemi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.iskalemi'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='kdv_dahil_mi',
            field=models.BooleanField(default=False, verbose_name='Bu fiyata KDV Dahil mi?'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='kdv_orani',
            field=models.FloatField(default=20, verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='kur_degeri',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='İşlem Kuru'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Amerikan Doları'), ('EUR', '€ Euro'), ('GBP', '£ İngiliz Sterlini')], default='TRY', max_length=3),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='tedarikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.tedarikci'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='teklif_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='teklifler/', verbose_name='Teklif PDF/Resim'),
        ),
    ]
