# Generated by Django 6.0 on 2026-01-06 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_giderkategorisi_options_alter_harcama_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giderkategorisi',
            options={'verbose_name_plural': 'Gider Tanımları'},
        ),
        migrations.AlterModelOptions(
            name='harcama',
            options={'verbose_name_plural': '4. Harcamalar'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. İmalat Türleri'},
        ),
        migrations.AlterModelOptions(
            name='odeme',
            options={'verbose_name_plural': '5. Ödemeler'},
        ),
        migrations.AlterModelOptions(
            name='tedarikci',
            options={'verbose_name_plural': 'Tedarikçiler'},
        ),
        migrations.AddField(
            model_name='odeme',
            name='cek_durumu',
            field=models.CharField(choices=[('beklemede', '⏳ Vadesi Bekleniyor'), ('odendi', '✅ Ödendi / Tahsil Edildi'), ('karsiliksiz', '❌ Karşılıksız / İptal')], default='beklemede', help_text='Sadece Çek ödemeleri için kullanılır.', max_length=20, verbose_name='Çek Durumu'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='ilgili_teklif',
            field=models.ForeignKey(blank=True, limit_choices_to={'durum': 'onaylandi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teklif'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='odeme_turu',
            field=models.CharField(choices=[('nakit', 'Nakit / Havale'), ('cek', 'Çek'), ('kk', 'Kredi Kartı')], default='nakit', max_length=10),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi'),
        ),
    ]
