# Generated by Django 6.0 on 2026-01-08 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_giderkategorisi_options_alter_harcama_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Malzeme Adı (Örn: Ø14 Demir)')),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('mt', 'Metre (mt)'), ('adam_saat', 'Adam/Saat'), ('goturu', 'Götürü (Toplu)')], default='adet', max_length=20)),
                ('kritik_stok', models.FloatField(default=10, verbose_name='Kritik Stok Uyarı Limiti')),
            ],
            options={
                'verbose_name_plural': 'Depo: Malzeme Tanımları',
            },
        ),
        migrations.CreateModel(
            name='Hakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakedis_no', models.PositiveIntegerField(default=1, verbose_name='Hakediş No')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('donem_baslangic', models.DateField(verbose_name='Dönem Başı')),
                ('donem_bitis', models.DateField(verbose_name='Dönem Sonu')),
                ('tamamlanma_orani', models.FloatField(help_text="Örn: 10 girerseniz işin %10'u bitmiş sayılır.", verbose_name='Bu Dönem Tamamlanma (%)')),
                ('malzeme_zayiati', models.FloatField(default=0, verbose_name='Malzeme / Zayiat Kesintisi (TL)')),
                ('diger_kesintiler', models.FloatField(default=0, verbose_name='Diğer Kesintiler (Avans/Stopaj vb.)')),
                ('onay_durumu', models.BooleanField(default=False, verbose_name='Hakediş Onaylandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teklif', models.ForeignKey(limit_choices_to={'durum': 'onaylandi'}, on_delete=django.db.models.deletion.CASCADE, related_name='hakedisler', to='core.teklif')),
            ],
            options={
                'verbose_name_plural': 'Şantiye: Taşeron Hakedişleri',
            },
        ),
        migrations.CreateModel(
            name='DepoHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('islem_turu', models.CharField(choices=[('giris', '📥 Depo Girişi (Satınalma)'), ('cikis', '📤 Depo Çıkışı (Kullanım)'), ('iade', '↩️ İade / Red (Kusurlu Mal)')], max_length=10)),
                ('miktar', models.FloatField(verbose_name='Miktar')),
                ('irsaliye_no', models.CharField(blank=True, max_length=50, verbose_name='İrsaliye No')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='Açıklama / Kullanılan Yer')),
                ('iade_sebebi', models.CharField(blank=True, max_length=200, verbose_name='Red Sebebi')),
                ('iade_aksiyonu', models.CharField(choices=[('yok', '-'), ('degisim', '🔄 Yenisi Gelecek (Borç Düşme)'), ('iptal', '⛔ İptal Et / Faturadan Düş (Borç Düş)')], default='yok', max_length=20, verbose_name='İade Sonucu')),
                ('kanit_gorseli', models.ImageField(blank=True, null=True, upload_to='depo_kanit/', verbose_name='Hasar/Kanıt Fotoğrafı')),
                ('tedarikci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tedarikci', verbose_name='Tedarikçi (Giriş ise)')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='core.malzeme')),
            ],
            options={
                'verbose_name_plural': 'Depo: Giriş/Çıkış Hareketleri',
            },
        ),
    ]
