# Generated by Django 6.0 on 2026-01-08 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_malzeme_hakedis_depohareket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalzemeTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='İstenen Miktar')),
                ('oncelik', models.CharField(choices=[('normal', '🟢 Normal'), ('acil', '🔴 Acil'), ('cok_acil', '🔥 ÇOK ACİL (İş Durdu)')], default='normal', max_length=10, verbose_name='Aciliyet Durumu')),
                ('proje_yeri', models.CharField(blank=True, max_length=200, verbose_name='Kullanılacak Yer (Örn: C Blok Zemin)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Notlar')),
                ('durum', models.CharField(choices=[('bekliyor', '⏳ Onay Bekliyor'), ('onaylandi', '✅ Onaylandı (Satınalmada)'), ('tamamlandi', '📦 Temin Edildi / Geldi'), ('red', '❌ Reddedildi')], default='bekliyor', max_length=20)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Talep Tarihi')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='core.malzeme')),
                ('talep_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden Mühendis')),
            ],
            options={
                'verbose_name_plural': 'Şantiye: Malzeme Talepleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
