# Generated by Django 6.0 on 2026-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_malzemetalep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depohareket',
            options={'verbose_name_plural': 'Depo: Giriş/Çıkış'},
        ),
        migrations.AlterModelOptions(
            name='hakedis',
            options={'verbose_name_plural': 'Taşeron Hakedişleri'},
        ),
        migrations.AlterModelOptions(
            name='malzeme',
            options={'verbose_name_plural': 'Malzeme Tanımları'},
        ),
        migrations.AlterModelOptions(
            name='malzemetalep',
            options={'ordering': ['-tarih'], 'verbose_name_plural': 'Malzeme Talepleri'},
        ),
        migrations.AddField(
            model_name='malzemetalep',
            name='onay_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onaylanma Zamanı'),
        ),
        migrations.AddField(
            model_name='malzemetalep',
            name='temin_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Temin/Teslim Zamanı'),
        ),
    ]
