# Generated by Django 6.0 on 2026-01-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_depohareket_options_alter_hakedis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depohareket',
            options={'verbose_name_plural': 'Depo Hareketleri'},
        ),
        migrations.AlterModelOptions(
            name='hakedis',
            options={'verbose_name_plural': 'Hakedişler'},
        ),
        migrations.AddField(
            model_name='teklif',
            name='malzeme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.malzeme', verbose_name='Malzeme (Satınalma)'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='miktar',
            field=models.FloatField(default=1, verbose_name='Teklif Miktarı'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='is_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.iskalemi', verbose_name='İş Kalemi (Taşeronluk)'),
        ),
    ]
