# Generated by Django 6.0 on 2026-01-09 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_depohareket_options_alter_hakedis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Depo Adı')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Lokasyon / Adres')),
                ('is_sanal', models.BooleanField(default=False, verbose_name='Sanal / Tedarikçi Deposu mu?')),
            ],
            options={
                'verbose_name_plural': 'Depo Tanımları',
            },
        ),
        migrations.AlterModelOptions(
            name='hakedis',
            options={'verbose_name_plural': 'Taşeron Hakedişleri'},
        ),
        migrations.AddField(
            model_name='teklif',
            name='teslimat_durumu',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor (Henüz Gelmedi)'), ('kismi', 'Kısmi Teslimat'), ('tamamlandi', 'Tamamlandı (Stoklara Girdi)'), ('sanal', 'Sanal Depoda (Tedarikçide Bekliyor)')], default='bekliyor', max_length=20, verbose_name='Teslimat Durumu'),
        ),
        migrations.AlterField(
            model_name='depohareket',
            name='islem_turu',
            field=models.CharField(choices=[('giris', '📥 Depo Girişi (Satınalma/Transfer)'), ('cikis', '📤 Depo Çıkışı (Kullanım/Transfer)'), ('iade', '↩️ İade / Red (Kusurlu Mal)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='kdv_orani',
            field=models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20'), (-1, 'Özel Matrah')], default=20, verbose_name='KDV Oranı'),
        ),
        migrations.AddField(
            model_name='depohareket',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.depo', verbose_name='İlgili Depo'),
        ),
        migrations.CreateModel(
            name='DepoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Transfer Miktarı')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Transfer Notu (Plaka vb.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hedef_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giris_transferleri', to='core.depo', verbose_name='Hedef Depo (Nereye?)')),
                ('kaynak_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cikis_transferleri', to='core.depo', verbose_name='Kaynak Depo (Nereden?)')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.malzeme', verbose_name='Taşınacak Malzeme')),
            ],
            options={
                'verbose_name': 'Depolar Arası Transfer',
                'verbose_name_plural': 'Depolar Arası Transfer',
            },
        ),
    ]
