# Generated by Django 6.0 on 2026-01-09 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_depo_alter_hakedis_options_teklif_teslimat_durumu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depohareket',
            options={'verbose_name': 'Hareket Geçmişi (Log)', 'verbose_name_plural': 'Hareket Geçmişi (Log)'},
        ),
        migrations.AlterModelOptions(
            name='depotransfer',
            options={'verbose_name': '8. Sevkiyat (Mal Kabul)', 'verbose_name_plural': '8. Sevkiyat (Mal Kabul)'},
        ),
        migrations.AlterModelOptions(
            name='harcama',
            options={'verbose_name_plural': '5. Harcamalar (Gider)'},
        ),
        migrations.AlterModelOptions(
            name='malzeme',
            options={'verbose_name': '7. Envanter (Stok Durumu)', 'verbose_name_plural': '7. Envanter (Stok Durumu)'},
        ),
        migrations.AlterModelOptions(
            name='odeme',
            options={'verbose_name_plural': '6. Ödemeler'},
        ),
        migrations.AlterModelOptions(
            name='teklif',
            options={'verbose_name': '3. Teklifler (Fiyat Toplama)', 'verbose_name_plural': '3. Teklifler (Fiyat Toplama)'},
        ),
        migrations.RemoveField(
            model_name='hakedis',
            name='teklif',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='ilgili_teklif',
        ),
        migrations.RemoveField(
            model_name='teklif',
            name='teslimat_durumu',
        ),
        migrations.AlterField(
            model_name='teklif',
            name='durum',
            field=models.CharField(choices=[('beklemede', '⏳ Beklemede (Fiyat Toplanıyor)'), ('onaylandi', '✅ Onaylandı (Siparişe Dönüştü)'), ('reddedildi', '❌ Reddedildi')], default='beklemede', max_length=20),
        ),
        migrations.CreateModel(
            name='SatinAlma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(blank=True, max_length=50, verbose_name='Fatura No')),
                ('fatura_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi')),
                ('teslimat_durumu', models.CharField(choices=[('bekliyor', 'Bekliyor (Henüz Gelmedi)'), ('kismi', 'Kısmi Teslimat'), ('tamamlandi', 'Tamamlandı (Stoklara Girdi)'), ('sanal', 'Sanal Depoda (Tedarikçide Bekliyor)')], default='bekliyor', max_length=20, verbose_name='Teslimat Durumu')),
                ('notlar', models.TextField(blank=True, verbose_name='Satınalma/Teslimat Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teklif', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satinalma_donusumu', to='core.teklif', verbose_name='İlgili Onaylı Teklif')),
            ],
            options={
                'verbose_name': '4. Satınalma (Kesinleşen)',
                'verbose_name_plural': '4. Satınalma (Kesinleşen)',
            },
        ),
        migrations.AddField(
            model_name='hakedis',
            name='satinalma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hakedisler', to='core.satinalma', verbose_name='İlgili Sözleşme/Sipariş'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='ilgili_satinalma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.satinalma', verbose_name='İlgili Satınalma / Fatura'),
        ),
    ]
