# Generated by Django 6.0.1 on 2026-01-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_depohareket_options_alter_depotransfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='talep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='core.malzemetalep', verbose_name='İlgili Talep'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='durum',
            field=models.CharField(choices=[('bekliyor', '⏳ Talep Açıldı (Onay Bekliyor)'), ('islemde', '🔍 Satınalma / Teklif Sürecinde'), ('onaylandi', '✅ Sipariş Verildi'), ('tamamlandi', '📦 Sahaya Geldi / Kapandı'), ('red', '❌ Reddedildi / İptal')], default='bekliyor', max_length=20),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='durum',
            field=models.CharField(choices=[('beklemede', '⏳ İncelemede'), ('onaylandi', '✅ Onaylandı (Sipariş)'), ('reddedildi', '❌ Reddedildi')], default='beklemede', max_length=20),
        ),
    ]
