# Generated by Django 6.0.1 on 2026-01-13 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teklif_talep_alter_malzemetalep_durum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malzemetalep',
            options={'ordering': ['-tarih'], 'verbose_name_plural': 'Malzeme ve Hizmet Talepleri'},
        ),
        migrations.AddField(
            model_name='malzemetalep',
            name='is_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='core.iskalemi', verbose_name='İş Kalemi (Hizmet/Taşeron)'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='durum',
            field=models.CharField(choices=[('bekliyor', '⏳ Talep Açıldı (Onay Bekliyor)'), ('islemde', '🔍 Satınalma / Teklif Sürecinde'), ('onaylandi', '✅ Sipariş Verildi'), ('tamamlandi', '📦 Temin Edildi / Geldi'), ('red', '❌ Reddedildi / İptal')], default='bekliyor', max_length=20),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='malzeme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='core.malzeme', verbose_name='Malzeme (Satınalma)'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='proje_yeri',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kullanılacak Yer'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='talep_eden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden'),
        ),
    ]
