# Generated by Django 6.0 on 2026-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_malzemetalep_options_malzemetalep_is_kalemi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzeme',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Teknik Özellikler / Notlar'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Genel Malzeme'), ('hirdavat', 'Hırdavat / Nalburiye'), ('elektrik', 'Elektrik & Aydınlatma'), ('mekanik', 'Mekanik & Tesisat'), ('insaat', 'Kaba İnşaat (Çimento/Demir)'), ('boya', 'Boya & Kimyasal'), ('demirbas', 'Demirbaş / Ekipman')], default='genel', max_length=20, verbose_name='Malzeme Grubu'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='kdv_orani',
            field=models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20'), (-1, 'Özel Matrah')], default=20, verbose_name='Varsayılan KDV (%)'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='marka',
            field=models.CharField(blank=True, help_text='Örn: Bosch, Vitra vb.', max_length=100, verbose_name='Marka / Model'),
        ),
    ]
