# Generated by Django 6.0 on 2026-01-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_malzeme_aciklama_malzeme_kategori_malzeme_kdv_orani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iskalemi',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='İş Tanımı / Teknik Şartname'),
        ),
        migrations.AddField(
            model_name='iskalemi',
            name='kdv_orani',
            field=models.IntegerField(choices=[(0, '%0'), (5, '%5'), (10, '%10'), (16, '%16'), (20, '%20'), (-1, 'Özel Matrah')], default=20, verbose_name='Varsayılan KDV (%)'),
        ),
        migrations.AlterField(
            model_name='iskalemi',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.kategori', verbose_name='Kategori'),
        ),
    ]
