# Generated by Django 6.0 on 2026-01-13 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_iskalemi_aciklama_iskalemi_kdv_orani_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satinalma',
            options={'verbose_name': '4. Satınalma & Siparişler', 'verbose_name_plural': '4. Satınalma & Siparişler'},
        ),
        migrations.RemoveField(
            model_name='satinalma',
            name='fatura_no',
        ),
        migrations.RemoveField(
            model_name='satinalma',
            name='fatura_tarihi',
        ),
        migrations.RemoveField(
            model_name='satinalma',
            name='notlar',
        ),
        migrations.AddField(
            model_name='satinalma',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='satinalma',
            name='siparis_tarihi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi'),
        ),
        migrations.AddField(
            model_name='satinalma',
            name='teslim_edilen',
            field=models.FloatField(default=0, verbose_name='Şuana Kadar Gelen'),
        ),
        migrations.AddField(
            model_name='satinalma',
            name='toplam_miktar',
            field=models.FloatField(default=0, verbose_name='Sipariş Edilen Toplam'),
        ),
        migrations.AlterField(
            model_name='satinalma',
            name='teklif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satinalma_donusumu', to='core.teklif', verbose_name='İlgili Teklif'),
        ),
        migrations.AlterField(
            model_name='satinalma',
            name='teslimat_durumu',
            field=models.CharField(choices=[('bekliyor', '🔴 Bekliyor (Hiç Gelmedi)'), ('kismi', '🟠 Kısmi Teslimat (Eksik Var)'), ('tamamlandi', '🟢 Tamamlandı (Hepsi Geldi)')], default='bekliyor', max_length=20),
        ),
    ]
