# Generated by Django 6.0 on 2026-01-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_satinalma_options_remove_satinalma_fatura_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depohareket',
            name='siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depo_hareketleri', to='core.satinalma', verbose_name='Bağlı Sipariş'),
        ),
    ]
