# Generated by Django 6.0.1 on 2026-01-14 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_iskalemi_kdv_orani_alter_malzeme_kdv_orani_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=50, verbose_name='Fatura No')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi')),
                ('miktar', models.FloatField(verbose_name='Fatura Edilen Miktar')),
                ('tutar', models.FloatField(verbose_name='Fatura Tutarı (KDV Dahil)')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='faturalar/', verbose_name='Fatura Görseli/PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.depo', verbose_name='Giriş Yapılacak Depo')),
                ('satinalma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturalar', to='core.satinalma', verbose_name='İlgili Sipariş')),
            ],
            options={
                'verbose_name': 'Alış Faturası',
                'verbose_name_plural': 'Alış Faturaları',
            },
        ),
    ]
