# Generated by Django 6.0.1 on 2026-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satinalma',
            name='teslim_edilen',
            field=models.FloatField(default=0, verbose_name='Şuana Kadar Gelen (Fatura)'),
        ),
    ]
