# Generated by Django 6.0.1 on 2026-01-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_satinalma_teslim_edilen'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalma',
            name='faturalanan_miktar',
            field=models.FloatField(default=0, verbose_name='Faturası Gelen (Finansal)'),
        ),
        migrations.AlterField(
            model_name='satinalma',
            name='teslim_edilen',
            field=models.FloatField(default=0, verbose_name='Depoya Giren (Fiziksel)'),
        ),
    ]
