# Generated by Django 6.0.1 on 2026-01-14 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_satinalma_faturalanan_miktar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hakedis',
            options={'ordering': ['-tarih'], 'verbose_name_plural': '6. Taşeron Hakedişleri'},
        ),
        migrations.RemoveField(
            model_name='hakedis',
            name='malzeme_zayiati',
        ),
        migrations.AddField(
            model_name='hakedis',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Yapılan İşin Açıklaması'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='avans_kesintisi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Avans Kesintisi'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='brut_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hakediş Tutarı (KDV Hariç)'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='kdv_orani',
            field=models.PositiveIntegerField(default=20, verbose_name='KDV (%)'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='kdv_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='KDV Tutarı'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='odenecek_net_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ödenecek Net Tutar'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='stopaj_orani',
            field=models.PositiveIntegerField(default=0, help_text='Genelde %3', verbose_name='Stopaj (%)'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='stopaj_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kesilen Stopaj'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='teminat_orani',
            field=models.PositiveIntegerField(default=0, help_text='Genelde %5 veya %10', verbose_name='Teminat (%)'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='teminat_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kesilen Teminat'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='diger_kesintiler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Malzeme/Ceza vb.'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='onay_durumu',
            field=models.BooleanField(default=False, verbose_name='Onaylandı'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='satinalma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hakedisler', to='core.satinalma', verbose_name='İlgili Sözleşme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='tamamlanma_orani',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bu Dönem İlerleme (%)'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Hakediş Tarihi'),
        ),
    ]
