# Generated by Django 6.0.1 on 2026-01-14 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_hakedis_options_remove_hakedis_malzeme_zayiati_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odeme',
            options={'ordering': ['-tarih'], 'verbose_name': '7. Ödeme & Çek Çıkışı', 'verbose_name_plural': '7. Ödeme & Çek Çıkışı'},
        ),
        migrations.RenameField(
            model_name='odeme',
            old_name='cek_banka',
            new_name='banka_adi',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='cek_durumu',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='cek_gorseli',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='cek_numarasi',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='cek_sube',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='cek_vade_tarihi',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='dekont',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='ilgili_satinalma',
        ),
        migrations.RemoveField(
            model_name='odeme',
            name='kur_degeri',
        ),
        migrations.AddField(
            model_name='odeme',
            name='bagli_hakedis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hakedis', verbose_name='İlgili Hakediş'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='cek_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Çek No / Dekont No'),
        ),
        migrations.AddField(
            model_name='odeme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odeme',
            name='vade_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Çek Vadesi'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='odeme_turu',
            field=models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale / EFT'), ('cek', 'Çek')], default='nakit', max_length=10, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tedarikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='core.tedarikci', verbose_name='Ödenen Firma'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tutar',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ödenen Tutar'),
        ),
    ]
