# Generated by Django 6.0.1 on 2026-01-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_odeme_options_rename_cek_banka_odeme_banka_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakedis',
            name='fiili_odenen_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Şu Ana Kadar Ödenen'),
        ),
        migrations.AddField(
            model_name='satinalma',
            name='fiili_odenen_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Şu Ana Kadar Ödenen'),
        ),
    ]
