# Generated by Django 6.0.1 on 2026-01-15 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_hakedis_fiili_odenen_tutar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giderkategorisi',
            options={'verbose_name': 'Gider Tanımı', 'verbose_name_plural': 'Gider Tanımları'},
        ),
        migrations.AlterModelOptions(
            name='harcama',
            options={'ordering': ['-tarih'], 'verbose_name': '5. Harcama (Gider)', 'verbose_name_plural': '5. Harcamalar (Gider)'},
        ),
        migrations.AddField(
            model_name='harcama',
            name='kur_degeri',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='İşlem Kuru'),
        ),
        migrations.AlterField(
            model_name='giderkategorisi',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Gider Kategorisi'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='donem_baslangic',
            field=models.DateField(blank=True, null=True, verbose_name='Dönem Başı'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='donem_bitis',
            field=models.DateField(blank=True, null=True, verbose_name='Dönem Sonu'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='aciklama',
            field=models.CharField(max_length=200, verbose_name='Harcama Açıklaması'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='dekont',
            field=models.FileField(blank=True, null=True, upload_to='harcamalar/', verbose_name='Dekont / Fiş'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcamalar', to='core.giderkategorisi', verbose_name='Gider Türü'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Amerikan Doları'), ('EUR', '€ Euro'), ('GBP', '£ İngiliz Sterlini')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Harcama Tarihi'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='tutar',
            field=models.FloatField(verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='marka',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marka / Model'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='is_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='core.iskalemi', verbose_name='İş Kalemi (Hizmet/Taşeron)'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='malzeme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='core.malzeme', verbose_name='Malzeme (Satınalma)'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='proje_yeri',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kullanılacak Yer'),
        ),
    ]
