# Generated by Django 6.0.1 on 2026-01-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_giderkategorisi_options_alter_harcama_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
    ]
