# Generated by Django 6.0.1 on 2026-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_odeme_para_birimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harcama',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3),
        ),
    ]
