# Generated by Django 6.0.1 on 2026-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_harcama_para_birimi_alter_odeme_para_birimi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depohareket',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='depotransfer',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transfer Miktarı'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fatura Edilen Miktar'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tutar',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fatura Tutarı (KDV Dahil)'),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='tutar',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='iskalemi',
            name='hedef_miktar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Yaklaşık Metraj'),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='kritik_stok',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Kritik Stok Uyarı Limiti'),
        ),
        migrations.AlterField(
            model_name='malzemetalep',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İstenen Miktar'),
        ),
        migrations.AlterField(
            model_name='satinalma',
            name='faturalanan_miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Faturası Gelen (Finansal)'),
        ),
        migrations.AlterField(
            model_name='satinalma',
            name='teslim_edilen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depoya Giren (Fiziksel)'),
        ),
        migrations.AlterField(
            model_name='satinalma',
            name='toplam_miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sipariş Edilen Toplam'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat (KDV Hariç)'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='miktar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Teklif Miktarı'),
        ),
    ]
