# Generated by Django 6.0.1 on 2026-01-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_depohareket_miktar_alter_depotransfer_miktar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='depo_turu',
            field=models.CharField(choices=[('MERKEZ', 'Merkez Depo'), ('BAGLANTI', 'Bağlantı Deposu (Sanal/Tedarikçi)'), ('KULLANIM', 'Kullanım Deposu (Sahada)')], default='MERKEZ', max_length=10, verbose_name='Depo Türü'),
        ),
    ]
