# Generated by Django 6.0.1 on 2026-01-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faturaodeme'),
        ('core', '0030_alter_depohareket_miktar_alter_depotransfer_miktar_and_more'),
    ]

    operations = [
    ]
